name: CI

# Only react on staging, this is the branch selected in the Paligo publishing setting. 
on:
  push:
    branches: [ markdown ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
        with:
          # fetch-depth 2 is required to look at the list of changed files in the shell script.
          fetch-depth: '2'
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          pandoc -v
 
      #Call a shell script that executes the logic of unzipping the publication and putting it in the correct place.
      - name: Unzip and convert
        run: ./.github/scripts/unzip-and-convert.sh
        shell: bash
          

