# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: List files
        run: |
          for file in $(git diff-tree -r $GITHUB_SHA --name-only --no-commit-id); do echo $file; done
      - name: Cat file
        run: cat $GITHUB_WORKSPACE/test.txt
      # Runs a single command using the runners shell
      - name: Unzip and move
        run: ./.github/scripts/unzip-and-move.sh
        shell: bash

